version: "3.9"

services:
  # Simple MQTT Test Service (no db dependency)
  # checks if ingestor is ... ingesting
  mqtt-test:
    image: alpine/curl
    container_name: mqtt-test-zigbee
    command: |
      sh -c "
      apk add --no-cache mosquitto-clients &&
      echo 'Testing MQTT connection to host broker...' &&
      mosquitto_sub -h 172.17.0.1 -t 'zigbee2mqtt/#' -v
      "
    networks:
      - mqtt-network
    restart: "no"

networks:
  mqtt-network:
    driver: bridge