version: "3.9"

services:
  # MQTT Broker (Mosquitto)
  mosquitto:
    build: ./mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"        # MQTT (dev)
      - "8883:8883"        # MQTT with TLS (prod)
      - "9001:9001"        # WebSocket (dev)
      - "9443:9443"        # WebSocket with TLS (prod)
    volumes:
      - mosq-data:/mosquitto/data
      - mosq-logs:/mosquitto/log
    environment:
      - TZ=Etc/UTC
    restart: unless-stopped
    networks:
      - mqtt-network

  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=iot
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mqtt-network

  # Go MQTT Ingestor Service
  ingestor:
    build: .
    container_name: mqtt-ingestor
    depends_on:
      mosquitto:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "9002:9002"        # HTTP health endpoint
    environment:
      # HTTP Server
      - PORT=9002
      
      # MongoDB Configuration
      - MONGODB_URI=mongodb+srv://maplesense2025_db_user:fOvb6SDjUbe3EAqE@cluster0.mt69wbz.mongodb.net/iot?retryWrites=true&w=majority&tls=true
      - DB_NAME=iot
      - COLL_NAME=readings
      
      # MQTT Broker Configuration (Dev)
      - BROKER_HOST=mosquitto
      - BROKER_PORT=1883
      - BROKER_TLS=false
      - BROKER_USER=
      - BROKER_PASS=
      - BROKER_CA_FILE=
      
      # MQTT Subscription Configuration
      - MQTT_TOPIC=sensors/#
      - MQTT_CLIENT_ID=go-ingestor-1
      - MQTT_SHARED_GROUP=
      
      # Batch Processing Configuration
      - BATCH_SIZE=200
      - BATCH_WINDOW=1s
      
      # Timezone
      - TZ=Etc/UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mqtt-network

  # Optional: MQTT Explorer for testing (development only)
  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-explorer
    ports:
      - "4000:4000"
    environment:
      - MQTT_EXPLORER_HOST=mosquitto
      - MQTT_EXPLORER_PORT=1883
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - mqtt-network
    profiles:
      - dev

volumes:
  mosq-data:
    driver: local
  mosq-logs:
    driver: local
  mongo-data:
    driver: local

networks:
  mqtt-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
