version: "3.9"

services:
  # MQTT Broker (Mosquitto) - Production
  mosquitto:
    build: 
      context: ./mosquitto
      dockerfile: Dockerfile
    container_name: mqtt-broker-prod
    ports:
      - "8883:8883"        # MQTT with TLS
      - "9443:9443"        # WebSocket with TLS
    volumes:
      - mosq-data:/mosquitto/data
      - mosq-logs:/mosquitto/log
      - ./mosquitto/certs:/mosquitto/certs:ro
      - ./mosquitto/config/passwd:/mosquitto/config/passwd:ro
      - ./mosquitto/config/acl:/mosquitto/config/acl:ro
    environment:
      - TZ=Etc/UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "$$SYS/broker/uptime", "-m", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mqtt-network

  # Go MQTT Ingestor Service - Production
  ingestor:
    build: .
    container_name: mqtt-ingestor-prod
    depends_on:
      mosquitto:
        condition: service_healthy
    ports:
      - "9002:9002"        # HTTP health endpoint
    environment:
      # HTTP Server
      - PORT=9002
      
      # MongoDB Configuration (External)
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME:-iot}
      - COLL_NAME=${COLL_NAME:-readings}
      
      # MQTT Broker Configuration (Production)
      - BROKER_HOST=mosquitto
      - BROKER_PORT=8883
      - BROKER_TLS=true
      - BROKER_USER=${BROKER_USER}
      - BROKER_PASS=${BROKER_PASS}
      - BROKER_CA_FILE=/certs/ca.crt
      
      # MQTT Subscription Configuration
      - MQTT_TOPIC=${MQTT_TOPIC:-sensors/#}
      - MQTT_CLIENT_ID=${MQTT_CLIENT_ID:-go-ingestor-prod}
      - MQTT_SHARED_GROUP=${MQTT_SHARED_GROUP:-ingestors}
      
      # Batch Processing Configuration
      - BATCH_SIZE=${BATCH_SIZE:-500}
      - BATCH_WINDOW=${BATCH_WINDOW:-500ms}
      
      # Timezone
      - TZ=Etc/UTC
    volumes:
      - ./mosquitto/certs:/certs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mqtt-network

volumes:
  mosq-data:
    driver: local
  mosq-logs:
    driver: local

networks:
  mqtt-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
